Repository vsakkas/sydney.py, pull requests merged in 2023-10, with the labels that each got.

#52 Fix conversationSignature key error
  sydney/constants.py
  sydney/sydney.py
Labels: bug

#58 Fix potential exception when fetching suggested responses
  README.md
  pyproject.toml
  sydney/sydney.py
Labels: bug

#59 Fix create conversation URL
  README.md
  pyproject.toml
  sydney/constants.py
Labels: bug

#60 Update cookie instructions
  README.md
Labels: documentation

#66 Refactor ask method and expand testing coverage
  README.md
  sydney/sydney.py
  tests/test_ask.py
  tests/test_compose.py
  tests/test_conversation.py
Labels: bug, enhancement

#67 Revamp and improve compose feature
  README.md
  sydney/enums.py
  sydney/sydney.py
  tests/test_compose.py
Labels: documentation, enhancement

#64 Image uploading to Bing Chat
  sydney/constants.py
  sydney/exceptions.py
  sydney/sydney.py
  tests/test_ask.py
Labels: enhancement

#72 Expand chat headers
  sydney/constants.py
Labels: enhancement

#73 Refactor attachment upload code
  README.md
  pyproject.toml
  sydney/sydney.py
Labels: enhancement

#75 Make cookies optional
  README.md
  sydney/sydney.py
Labels: documentation, enhancement

#80 Fix image upload blobID handling
  sydney/enums.py
  sydney/sydney.py
Labels: bug, enhancement

#81 Add web context parameter on ask
  README.md
  pyproject.toml
  sydney/sydney.py
Labels: documentation, enhancement
